made contributors.md
anitab-org/vms pull request #1059
Opened 2020-09-01 04:10 UTC by vaibhavarora102

# Description
added the contributors.md file and installed all-contributors bot as a part of the open-source hack
Fixes  #1028

# Type of Change:
**Delete irrelevant options.**

- Documentation

# How Has This Been Tested?
just added a readme file

# Checklist:
**Delete irrelevant options.**

- [/ ] My PR follows the style guidelines of this project
- [/ ] I have performed a self-review of my own code or materials
- [ /] I have made corresponding changes to the documentation
- [ /] Any dependent changes have been merged  (no dependencies)

2020-09-01 11:04 UTC, Kajol-Kumari commented
Hey @vaibhavarora102 thanks for the PR but I think this bot won't work untill we provide them the read and write access of the `vms` main repo. So, I am currently looking for a way to implement it. Meanwhile you can work on the other issue.

2020-09-01 11:05 UTC, vaibhavarora102 commented
Oh thanks for information

2020-09-03 13:01 UTC, Kajol-Kumari requested changes
@vaibhavarora102 as you can't install bot due to permission requirement. please go for adding the contributors list in the `contributors.md` file manually. We will install bot for the repo later on.

2020-09-03 13:17 UTC, vaibhavarora102 commented
Can you pls tell the format in which I had to write

2020-09-03 14:56 UTC, Kajol-Kumari commented
> Can you pls tell the format in which I had to write

@vaibhavarora102 keep it in tabular form having details like contributor's name, their github profile link and the number of commits they have made.

2020-09-03 15:19 UTC, vaibhavarora102 commented
Should I close this pr and add another one?

2020-09-03 15:34 UTC, vaibhavarora102 commented
okay

2020-09-04 07:05 UTC, vaibhavarora102 commented
hi @Kajol-Kumari I had done all my work 
kindly review it and approve for merge

2020-09-04 11:27 UTC, Kajol-Kumari requested changes
please rename the file as `CONTRIBUTORS.md` as all the `.md` files have names in this format only

2020-09-04 11:27 UTC, Kajol-Kumari commented on Contributors.md
> +## Thankyou all for your contributions!
please provide a space in `Thankyou` i.e make it like `Thank you`

2020-09-04 12:22 UTC, vaibhavarora102 commented
@Kajol-Kumari  can you pls check now

2020-09-04 12:48 UTC, Kajol-Kumari submitted a review, later dismissed
LGTM :+1:  
@vaibhavarora102 please squash the commits into a single commit so that it can be sent for final approval.

2020-09-04 14:46 UTC, vaibhavarora102 commented
Kindly now take it for final review

2020-09-04 18:56 UTC, Kajol-Kumari commented
> Kindly now take it for final review
Hey @vaibhavarora102 I can see still 8 commits in this PR please squash them in a single one.

2020-09-05 18:09 UTC, SanketDG approved these changes
Looks good to me, was this done manually?

2020-09-06 08:30 UTC, vaibhavarora102 commented
Hi @Kajol-Kumari 
Can I expect now my pr to get merged soon

2020-09-06 13:58 UTC, SanketDG commented
I don't like this being done manually, why not just use https://allcontributors.org/docs/en/cli/overview for now, and then we can see if we can get the bot integrated by some maintainer.

2020-09-06 15:55 UTC, Kajol-Kumari commented
> I don't like this being done manually, why not just use https://allcontributors.org/docs/en/cli/overview for now, and then we can see if we can get the bot integrated by some maintainer.



> I don't like this being done manually, why not just use https://allcontributors.org/docs/en/cli/overview for now, and then we can see if we can get the bot integrated by some maintainer.

@SanketDG If we go on adding with this ^ then:
1. It will just add extra dev-dependency which we won't require after the bot installation.
2. I am not sure, if we would be able to create the contributor list using this CLI from a fork repo. for the main repo.using this ^

2020-09-06 15:56 UTC, Kajol-Kumari commented
> Hi @Kajol-Kumari
> Can I expect now my pr to get merged soon

@vaibhavarora102 All the PRs having 2 or more approvals will be merged but only after the event ends. So, if your PR has got atleast two approvals, it's good to go and you can work on other PRs.

2020-09-06 16:09 UTC, vaibhavarora102 commented
Actually it was on my default branch 
So, I could only work freely once it's merged

And I think it's been approved by 2 times and it's a kind request to merge if everything is well

2020-09-06 16:59 UTC, Kajol-Kumari commented
Hey @vaibhavarora102 we can't merge any of the PR before the end of the event and participants are always supposed to create a branch and then start working on an issue. SO i would recommend you to make a fresh fork, create a branch, make th erequired changes , close this Pr and open up a new one.

2020-09-06 18:01 UTC, SanketDG commented
> 1. It will just add extra dev-dependency which we won't require after the bot installation.

I am not sure I follow, I am asking for the cli to be used once to generate the files in README.md and then send the PR.
Exactly what's being done now, except through a tool and not manually.

> 2\. I am not sure, if we would be able to create the contributor list using this CLI from a fork repo. for the main repo.using this ^

Again, I do not follow, it's just like changing a file and sending a PR right? The diff would be against README.md

---

Later we just integrate this with the bot itself (when a maintainer does this)

2020-09-06 18:17 UTC, Kajol-Kumari commented
> > 1. It will just add extra dev-dependency which we won't require after the bot installation.
> 
> I am not sure I follow, I am asking for the cli to be used once to generate the files in README.md and then send the PR.
> Exactly what's being done now, except through a tool and not manually.
> 
> > 2. I am not sure, if we would be able to create the contributor list using this CLI from a fork repo. for the main repo.using this ^
> 
> Again, I do not follow, it's just like changing a file and sending a PR right? The diff would be against README.md
> 
> Later we just integrate this with the bot itself (when a maintainer does this)

@SanketDG I hadn't got your proposal properly. This sounds good to me. @vaibhavarora102 can you please integrate the CLI and create the contributor list using that only. Also as you have created this PR using your master branch. Please clone this one and make a new PR through a particular branch dedicated for this issue.

2020-09-10 15:30 UTC, closed without merging