docs: Added the Python version Badge and Logos to badges fixes: #1052
anitab-org/vms pull request #1067
Opened 2020-09-01 09:05 UTC by atharwa-24

# Description
Added the Python version badge to the README file. Additionally added logos to the Travis ,Zulip and Python Badge in README file.

Fixes #1052 

# Type of Change:
doc:

- Documentation

# How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
## before
![vms before badge](https://user-images.githubusercontent.com/54115798/91830367-4fea6b80-ec60-11ea-8887-34d345f0af60.PNG)

## after
![vms after badge](https://user-images.githubusercontent.com/54115798/91830393-57aa1000-ec60-11ea-84cb-5003fc8229e2.PNG)

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-09-01 17:57 UTC, rkpattnaik780 requested changes
Functionality has been added. Just a minor change is required for approval.

2020-09-01 17:57 UTC, rkpattnaik780 commented on README.md
> +
Remove this blank line.

2020-09-01 17:57 UTC, rkpattnaik780 commented on README.md
> +
Remove this blank line.

2020-09-01 19:12 UTC, atharwa-24 commented
Hey thanks for this one i wasn't known to the concept of Updating pull requests 
learnt to apply the changes in the existing PR

2020-09-01 19:20 UTC, SanketDG approved these changes
Looks good to me, if you can squash the commits I will merge this!

2020-09-01 19:21 UTC, atharwa-24 commented
ok @SanketDG

2020-09-01 19:37 UTC, atharwa-24 commented
@SanketDG Done

2020-09-02 09:18 UTC, atharwa-24 commented
@SanketDG @rkpattnaik780 Please review the changes

2020-09-02 09:39 UTC, rkpattnaik780 commented on README.md
> +[![Build Status](https://img.shields.io/travis/anitab-org/vms/develop?logo=travis)](https://travis-ci.org/anitab-org/vms)
Keep one new line after the second line. Earlier commits had two lines hence I asked to remove one.

2020-09-02 09:43 UTC, rkpattnaik780 commented
Add “fixes #” in the commit body as well.

2020-09-02 11:46 UTC, closed without merging

2020-09-02 11:47 UTC, rkpattnaik780 commented
The commits needed to be squashed, any reason you closed this PR @atharwa-24

2020-09-02 11:50 UTC, atharwa-24 commented
i had messed up while squashing the PR @rkpattnaik780

2020-09-02 11:51 UTC, atharwa-24 commented
I will make the changes and will put a new PR

2020-09-02 11:56 UTC, rkpattnaik780 commented
Try to fix this PR. Let me know if you need help.

2020-09-02 11:59 UTC, atharwa-24 commented
> Try to fix this PR. Let me know if you need help.

I tried to fix that one but its not reopening

2020-09-02 12:00 UTC, atharwa-24 commented
Can we just select certain commits and make the PR

2020-09-02 12:02 UTC, rkpattnaik780 commented
> Can we just select certain commits and make the PR

Okay, make a fresh PR then.