Added button in UI to link Zulip
anitab-org/vms pull request #1089
Opened 2020-09-04 11:16 UTC by yash2189

# Description
To add button in UI to link Zulip
Fixes #1038

# Type of Change:
- User Interface

# How Has This Been Tested?
Successfully added button in UI to link Zulip. When a registered user is logged in the button is shown on the home page.

Screenshots:
![Button_ZULIP](https://user-images.githubusercontent.com/31548778/92205710-de026400-eea3-11ea-9dd0-294152dc1bd3.PNG)

# Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

2020-09-04 11:56 UTC, keshakaneria commented on vms/home/templates/home/home.html
> +          <button type="button" class="btn btn-primary btn-lg">Connect With us 			on Zulip</button></a>
There seems an unnecessary spacing after 'us'. You need to remove it.

2020-09-04 12:07 UTC, keshakaneria requested changes

2020-09-04 12:07 UTC, keshakaneria commented on vms/home/templates/home/home.html
> +          <button type="button" class="btn btn-primary btn-lg">Connect With us 			on Zulip</button></a>
Also check if the button's position and size is responsive or not.

2020-09-04 13:39 UTC, yash2189 commented
@keshakaneria  I have checked it please review it again.

2020-09-04 15:35 UTC, keshakaneria commented
Also can you let me know why was the images added in docs/screenshots file?

2020-09-04 15:55 UTC, yash2189 commented
I thought the screenshot would be required hence I did. Does it have to be removed or placed in different folder?

2020-09-04 17:00 UTC, keshakaneria commented
> I thought the screenshot would be required hence I did. Does it have to be removed or placed in different folder?
> However I have placed them in a separate folder now called UI_screenshots.
> If this is fine?

Well we don't need any screenshots to be uploaded in the repo how the UI looks. So it is better if we dont add any of the screenshots in commits. There should be only the code changed in `home.html` and nothing else. So remove all those screenshots and push it for the final review.
Points to change:
- Remove the screenshots
- Squash the final commits
Hence it will be ready to merge. Otherwise great job @yash2189 ! 👍 :)

2020-09-04 19:22 UTC, yash2189 commented
Surely @keshakaneria I'll do that by tomorrow if that works?

2020-09-05 06:34 UTC, yash2189 commented
@keshakaneria would you please tell me how do I squash those final commits , I haven't used the squash command before.

2020-09-05 06:47 UTC, keshakaneria commented
> @keshakaneria would you please tell me how do I squash those final commits , I haven't used the squash command before.

Refer this for squashing https://www.internalpointers.com/post/squash-commits-into-one-git. You'll get to know how it is done.

2020-09-05 07:30 UTC, yash2189 commented
@keshakaneria  I have squashed the commits.

2020-09-05 08:35 UTC, keshakaneria commented
> @keshakaneria I have squashed the commits.
> Would you please check whether I have done it correctly?

The commits count still shows me 4. After squashing it will change to a single commit. Try once more if you are able to do.

2020-09-05 09:18 UTC, yash2189 commented
Can I please close this PR and make a new PR instead I'd be able to do that quick

2020-09-05 09:30 UTC, closed without merging

2020-09-05 09:33 UTC, keshakaneria commented
I guess this is not good for you to open 3 PRs for an individual issue. Take care next time if any issue assigned to you.

2020-09-05 09:44 UTC, yash2189 commented
Apologies,I will improve on this surely.

2020-09-05 09:47 UTC, yash2189 commented
@keshakaneria  Can you please review this PR #1091 ?