New input
anitab-org/vms pull request #1098
Opened 2020-09-08 09:13 UTC by psingh587

# Description
In Sign Up Admin, I have made the city and state input disabled until the country is filled first. The city is disabled until the state is filled first.

Fixes #1050 

# Type of Change:
- User Interface

# How Has This Been Tested?
Checked in my local server. Works well according to me. I have handled all the scenarios.
![inputVMS](https://user-images.githubusercontent.com/51945896/92457160-846ea200-f1e1-11ea-9f23-f378e81a5360.gif)

# Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code.

2020-09-09 07:31 UTC, rkpattnaik780 requested changes
I guess this code has some unnecessary checks and can be improved. We can achieve the change in fewer lines of code. Furthermore, these changes dont seem to work properly

2020-09-09 07:31 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_city.js
> +		var state =document.getElementById("select_state");
If we have jquery already, use `$` instead of `document.getElementBy-`.

2020-09-09 07:31 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_state.js
> +
Remove these extra lines.

2020-09-09 09:14 UTC, psingh587 commented
> I guess this code has some unnecessary checks and can be improved. We can achieve the change in fewer lines of code. Furthermore, these changes dont seem to work properly

Alright , I Will make the required modification. Could you tell me what is not working properly with these changes?  Do I need to put some more to the code apart from changing it to jQuery?

2020-09-09 09:28 UTC, rkpattnaik780 commented
> > I guess this code has some unnecessary checks and can be improved. We can achieve the change in fewer lines of code. Furthermore, these changes dont seem to work properly
> 
> Alright , I Will make the required modification. Could you tell me what is not working properly with these changes? Do I need to put some more to the code apart from changing it to jQuery?

Initially the state and city dropdowns are not disabled.

2020-09-11 09:27 UTC, psingh587 commented
> > > I guess this code has some unnecessary checks and can be improved. We can achieve the change in fewer lines of code. Furthermore, these changes dont seem to work properly
> > 
> > 
> > Alright , I Will make the required modification. Could you tell me what is not working properly with these changes? Do I need to put some more to the code apart from changing it to jQuery?
> 
> Initially the state and city dropdowns are not disabled.

As per the GIF, it is happening in mine.

2020-09-11 10:29 UTC, rkpattnaik780 commented
> > > > I guess this code has some unnecessary checks and can be improved. We can achieve the change in fewer lines of code. Furthermore, these changes dont seem to work properly
> > > 
> > > 
> > > Alright , I Will make the required modification. Could you tell me what is not working properly with these changes? Do I need to put some more to the code apart from changing it to jQuery?
> > 
> > 
> > Initially the state and city dropdowns are not disabled.
> 
> As per the GIF, it is happening in mine.

It is rather weird, if I run the app and navigate to admin signup through homepage, the dropdowns are not disbled by default. Can you show me a gif showing the dropdowns just after navigating t that page?

2020-09-13 03:23 UTC, psingh587 commented
> > > > > I guess this code has some unnecessary checks and can be improved. We can achieve the change in fewer lines of code. Furthermore, these changes dont seem to work properly
> > > > 
> > > > 
> > > > Alright , I Will make the required modification. Could you tell me what is not working properly with these changes? Do I need to put some more to the code apart from changing it to jQuery?
> > > 
> > > 
> > > Initially the state and city dropdowns are not disabled.
> > 
> > 
> > As per the GIF, it is happening in mine.
> 
> It is rather weird, if I run the app and navig

ate to admin signup through homepage, the dropdowns are not disbled by default. Can you show me a gif showing the dropdowns just after navigating t that page?
@rkpattnaik780 
Hello.
Sorry for the delay in responding.
![newTEXTREVIEW](https://user-images.githubusercontent.com/51945896/93009417-7385ae00-f59e-11ea-8609-2ad1567759f6.gif)

2020-09-13 07:52 UTC, rkpattnaik780 commented
Hello @psingh587 . Can you please check if all your commits have been pushed cause I am not able to see it locally after pulling your PR. Furthermore, do address the other review comments, give appropriate spacing link `x = a` and not `x =a`. Squash your commits as well.

2020-09-15 07:46 UTC, rkpattnaik780 commented
@psingh587 any update?

2020-09-15 16:24 UTC, psingh587 commented
> @psingh587 any update?

Really sorry for the delay. There were some technical issues with my laptop. I will work upon this commit tonight and get back to you.

2020-09-16 05:31 UTC, psingh587 commented
@rkpattnaik780 
I have made the file changes. It handles all the scenarios. Please check.

2020-09-16 19:16 UTC, rkpattnaik780 requested changes
Thanks for these changes. It handles all the scenarios. Please make this PR cleaner, there are many unnecessary log statements that need to be removed and please indent properly. You are also required to squash your commits.

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/registration/templates/registration/signup_administrator.html
> +
Remove this unnecessary blank line.

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_city.js
> +		var city = $("#select_city"); if(state.prop('disabled') === false) console.log("yessss",state.val())
Place this if statement in a proper position.

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_city.js
> +		var city = $("#select_city"); if(state.prop('disabled') === false) console.log("yessss",state.val())
Remove console log as well.

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_city.js
> +		if(state.prop('disabled') === false && state.val() !== null && state.val() !== "0") { console.log("ji")
Remove console log

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_state.js
> +console.log("hi")
Remove console.log

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_state.js
> + console.log(state.val())
Remove console.log

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_state.js
> +               				city.html(cities);
Fix the indentation here.

2020-09-16 19:16 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_state.js
> +        });
Remove this extra space.

2020-09-18 12:51 UTC, rkpattnaik780 commented on vms/vms/static/vms/js/load_city.js
> +		if(state.val() !== "0" && state.val()!==null && state.prop('disabled') === false) {
Fix the indentation of this if/else block, we shouldn't have two tabs here. Sqaush the commits as well.

2020-09-21 17:55 UTC, psingh587 commented
Hey!
I have raised another PR and closing this one. The commits here went a bit bogus and I was not able to squash them.
#1124

2020-09-21 17:55 UTC, closed without merging